services:
    rocksolid_frontend_helper.frontend_hooks:
        class: MadeYourDay\RockSolidFrontendHelper\FrontendHooks
    rocksolid_frontend_helper.backend_hooks:
        class: MadeYourDay\RockSolidFrontendHelper\BackendHooks
