services:

    _instanceof:
        Contao\CoreBundle\Framework\FrameworkAwareInterface:
            calls:
                - ["setFramework", ["@contao.framework"]]

    MadeYourDay\RockSolidFrontendHelper\Controller\:
        resource: '../../Controller'
        public: true
        tags: ['controller.service_arguments']

    rocksolid_frontend_helper.frontend_hooks:
        class: MadeYourDay\RockSolidFrontendHelper\FrontendHooks
        arguments:
            - "@rocksolid_frontend_helper.element_builder"
            - "%rocksolid_frontend_helper.backend_modules%"

    rocksolid_frontend_helper.backend_hooks:
        class: MadeYourDay\RockSolidFrontendHelper\BackendHooks

    rocksolid_frontend_helper.element_provider:
        class: MadeYourDay\RockSolidFrontendHelper\ElementProvider
        public: false
        tags:
            - { name: rocksolid_frontend_helper.element_provider, priority: 192 }

    rocksolid_frontend_helper.element_builder:
        class: MadeYourDay\RockSolidFrontendHelper\ElementBuilder
